<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="unittest.loader._FailedTest-20180111204131" skipped="0" tests="1" time="0.000">
	<testcase classname="unittest.loader._FailedTest" name="calcula_tests" time="0.000">
		<error message="Failed to import test module: calcula_tests
Traceback (most recent call last):
  File &quot;/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/fjorg1/Labs/mentoring/src/unittest/python/calcula_tests.py&quot;, line 2, in &lt;module&gt;
    from src.main.python.calcula import Calcula
ModuleNotFoundError: No module named 'src'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: calcula_tests
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/fjorg1/Labs/mentoring/src/unittest/python/calcula_tests.py", line 2, in <module>
    from src.main.python.calcula import Calcula
ModuleNotFoundError: No module named 'src'

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
