
Running tests...
----------------------------------------------------------------------
....EE
======================================================================
ERROR [0.001s]: test_replace_flamarion_lucio (json_cabuloso_tests.TestKeyReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fjorg1/Labs/mentoring/src/unittest/python/json_cabuloso_tests.py", line 10, in test_replace_flamarion_lucio
    result = i.change_json()
  File "/Users/fjorg1/Labs/mentoring/src/main/python/json_cabuloso.py", line 18, in change_json
    with open(self.file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test1.json'

======================================================================
ERROR [0.000s]: test_replace_key_not_found (json_cabuloso_tests.TestKeyReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fjorg1/Labs/mentoring/src/unittest/python/json_cabuloso_tests.py", line 15, in test_replace_key_not_found
    result = i.change_json()
  File "/Users/fjorg1/Labs/mentoring/src/main/python/json_cabuloso.py", line 18, in change_json
    with open(self.file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test2.json'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=2)

Generating XML reports...
